Add boot and run check

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,6 +19,38 @@ jobs:
             ./build-images.sh
             docker images
             echo 'export DOCKER_PASS=$DOCKER_TOKEN' >> $BASH_ENV
+      - run:
+          name: "Install Test Prerequisites"
+          command: apk add mysql-client
+      - run: 
+          name: "Test Docker Images"
+          shell: /bin/bash -o pipefail
+          command: |
+            ssh -f -N -L localhost:3306:localhost:3306 remote-docker
+            IMAGES=$(docker images --format='{{.Repository}}:{{.Tag}}' | grep -Eo "cimg/mysql:[0-9]+\.[0-9]+\.[0-9]+")
+            for IMAGE in $IMAGES; do
+              printf "Booting $IMAGE...\n"
+              CONTAINER_ID=$(docker run --rm --env MYSQL_USER=user --env MYSQL_PASSWORD=passw0rd -p 3306:3306 -d $IMAGE)
+              for i in {1..20}; do
+                printf "[$i/20] Checking MySQL is up...\n"
+                mysqladmin ping -h 127.0.0.1 --silent
+                if [ $? -eq 0 ]; then
+                  printf "Booted $IMAGE!\n"
+                  break
+                elif [ $? -ne 0 ] && [ $i -eq 36 ]; then
+                  printf "Failed to boot image\n"
+                  exit 1
+                fi
+                printf "[$i/20] No response. Sleeping 10s...\n"
+                sleep 10s
+              done
+              printf "Running Test Command...\n"
+              mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT VERSION();"
+              printf "Stopping $IMAGE...\n"
+              docker stop $CONTAINER_ID >/dev/null 2>&1
+            done
+            printf "All images passed!\n"
+
       - deploy:
           name: "Publish Docker Images (main branch only)"
           command: |
